### ISSUE TITLE
timestamp_field error with unix type.

### ISSUE THREAD

**Issue by qingxp9** [Yelp/elastalert#1144] opened 2017-06-05 08:40 UTC
```
ERROR:root:Error running query: TransportError(400, u'search_phase_execution_exception', u'failed to parse date
 field [1.496638310584814E9] with format [epoch_second]')
```
How can i solve it?

**Comment by Qmando** [comment] 2017-06-05 17:43
I think this is an Elasticsearch issue: https://github.com/elastic/elasticsearch/issues/21489

See discussion from https://github.com/Yelp/elastalert/issues/996

I'm not actually sure how to solve it

**Comment by Qmando** [comment] 2017-07-27 21:23
Closing as duplicate of #996

**Closed by Qmando** 2017-07-27 21:23 UTC
