### ISSUE TITLE
Elastalert run as service 

### ISSUE THREAD

**Issue by windowsansiblernew** [Yelp/elastalert#1134] opened 2017-05-30 15:06 UTC
i followed this thread for running elastalert as service in ubuntu through systemd but it keeps failing, any help?
https://github.com/Yelp/elastalert/issues/194

**Comment by Qmando** [comment] 2017-05-30 18:28
Please give more information. What is failing.

**Comment by windowsansiblernew** [comment] 2017-05-31 07:23
i was trying systemd in ubuntu, can we run elastalert as service in amazon linux?

**Comment by Qmando** [comment] 2017-05-31 17:00
You still haven't given any information as to how it's failing or what exactly you tried. You can run it as a service under any type of Linux, provided you've got the right service config file or init script.

**Comment by windowsansiblernew** [comment] 2017-06-01 08:35
i got this resolved by moving to a new server..thanks for your time :)

**Comment by Qmando** [comment] 2017-08-15 18:08
Duplicate of #194

**Closed by Qmando** 2017-08-15 18:08 UTC
