### ISSUE TITLE
Query aggregation

### ISSUE THREAD

**Issue by gopalganu** [Yelp/elastalert#369] opened 2016-01-11 08:45 UTC
I want to get aggregation from ES and then implement a custom rule to use the aggregation.
How can I specify it in the yaml file (if I can) and if not is there any other way ?

**Comment by Qmando** [comment] 2016-01-14 01:01
Basic terms aggregation is supported. Look for ``use_terms_query`` in the documentation. Beyond that, custom aggregations are not supported. Closing as duplicate of #169

**Closed by Qmando** 2016-01-14 01:01 UTC
