### ISSUE TITLE
ES5. Error when trying to use aggregation

### ISSUE THREAD

**Issue by strtoreal** [Yelp/elastalert#870] opened 2017-01-16 19:19 UTC
Hi, I'm running **ES 5** + elastalert branch **support_es5**.

I have the following rule, where I try to use "aggregation" option (I need one alert for multiple matches):

```
es_host: localhost
es_port: 9200

name: Rule Name
type: any
index: logstash-*

filter:
- term:
    type: "sync.error"

aggregation:
  minutes: 5

realert:
  minutes: 0

alert:
- "slack"
alert_subject: "Issue occurred with consumer {0} at {1}"
alert_subject_args:
- field
- "@timestamp"
slack:
slack_webhook_url: "https://hooks.slack.com/services/...."
```

But when I run elastalert I see an error:

```
elastalert_error - 
{'message': "Error searching for pending aggregated matches: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')", 
'traceback': ['Traceback (most recent call last):', '  
File "/usr/local/lib/python2.7/dist-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 1179, in find_pending_aggregate_alert', '    size=1)', '  
File "build/bdist.linux-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped', '    return func(*args, params=params, **kwargs)', '  
File "build/bdist.linux-x86_64/egg/elasticsearch/client/__init__.py", line 539, in search', "    doc_type, '_search'), params=params, body=body)", '  
File "build/bdist.linux-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  
File "build/bdist.linux-x86_64/egg/elasticsearch/connection/http_requests.py", line 84, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  
File "build/bdist.linux-x86_64/egg/elasticsearch/connection/base.py", line 113, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)',
"RequestError: TransportError(400, u'parsing_exception', u'Unknown key for a START_OBJECT in [filter].')"], 'data': {'rule_name': 'Rule Name'}}
```

If I comment "aggregation" section, then I have several alerts (one alert for each match). 

Thanks in advance.

**Comment by cwhenderson20** [comment] 2017-02-02 05:50
I am also having this issue with aggregations on the `support_es5` branch. 

It appears as though the error is in the `find_pending_aggregate_alert` method (line 1170 at the time of this writing). I've played around with variants of the bool query via the DevTools Console in Kibana and many of them work. However, when I attempt to replace the current query that elastalert uses with one that works in Kibana, I get similar error messages. 

One query that works (and returns results) in Elasticsearch but that errors in elastalert is:
```json
{
  "query": {
    "bool": {
      "must": [{ "term": { "rule_name": "High latency routes" } },
        { "range": { "alert_time": { "gt": "2017-02-02T04:58:18.542Z" } } },
        { "not": { "exists": { "field": "aggregate_id" } } },
        { "term": { "alert_sent": "false" } }
      ]
  }},
  "sort": { "alert_time": { "order": "desc" } }
}
```
This gives the error: `Error searching for pending aggregated matches: TransportError(400, 'parsing_exception', 'no [query] registered for [not]')`

**Comment by Qmando** [comment] 2017-02-02 18:09
You can't use ``not`` anymore. Replace that filter with a query string ``NOT _exists_:

**Comment by cwhenderson20** [comment] 2017-02-02 18:20
Thanks for the response @Qmando. I think maybe my explanation wasn't clear. My yaml file is set up like @strtoreal's except that I'm searching for a range of values. When I run it in test mode, many hits are returned, so elastalert is formatting the initial query correctly. However, the aggregation configuration is what seems to cause the error mentioned above. I followed the stacktrace and found the method in elastalert that throws. Then I copied the query that elastalert uses to search for a pending agggregation alert. Elasticsearch gives the same error about an `unknown key for START_OBJECT in [filter]` when I run that resulting query directly. 

However, the above example that I gave of an elasticsearch query is one that _does_ work and return results from the elastalert_status index.

**Comment by cwhenderson20** [comment] 2017-02-02 18:22
In other words, I believe it's the internal query for the aggregation alert that's causing the error, not the user-entered query for searching the data.

**Comment by Qmando** [comment] 2017-02-02 18:28
Nevermind that comment. I accidentally posted it and erased it. I know what the issue is and it will be fixed very shortly

**Comment by cwhenderson20** [comment] 2017-02-02 18:40
Apologies. I saw that it was deleted just after I posted my follow up. Thank you!

**Closed** 2017-02-02 21:43 UTC

**Comment by cwhenderson20** [comment] 2017-02-03 23:18
I've pulled down the latest changes and have again tested the aggregation query, but now I get a new error: `parsing_exception', 'no [query] registered for [not]'`. I am running the latest version of Elasticsearch (5.2.0).

Here is my yaml config file:

```yaml
name: High latency routes
index: logstash-*
type: any
filter:
  - range:
      metric.requestTime:
        from: 4000
aggregation:
  weeks: 1
include:
  - metric.url
  - metric.statusCode
  - metric.method
  - hostname
  - metric.requestTime
alert:
  - slack
slack_webhook_url: <url>
```

And here is the final output from elastalert when running it in test mode:

```
Would have written the following documents to writeback index (default is elastalert_status):

silence - {'rule_name': 'High latency routes', '@timestamp': datetime.datetime(2017, 2, 3, 23, 14, 23, 427147, tzinfo=tzutc()), 'exponent': 0, 'until': datetime.datetime(2017, 2, 3, 23, 15, 23, 427134, tzinfo=tzutc())}

elastalert_error - {'message': "Error searching for pending aggregated matches: TransportError(400, u'parsing_exception', u'no [query] registered for [not]')", 'traceback': ['Traceback (most recent call last):', '  File "/usr/local/lib/python2.7/site-packages/elastalert-0.1.4-py2.7.egg/elastalert/elastalert.py", line 1185, in find_pending_aggregate_alert', '    size=1)', '  File "build/bdist.macosx-10.12-x86_64/egg/elasticsearch/client/utils.py", line 69, in _wrapped', '    return func(*args, params=params, **kwargs)', '  File "build/bdist.macosx-10.12-x86_64/egg/elasticsearch/client/__init__.py", line 539, in search', "    doc_type, '_search'), params=params, body=body)", '  File "build/bdist.macosx-10.12-x86_64/egg/elasticsearch/transport.py", line 327, in perform_request', '    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)', '  File "build/bdist.macosx-10.12-x86_64/egg/elasticsearch/connection/http_requests.py", line 84, in perform_request', '    self._raise_error(response.status_code, raw_data)', '  File "build/bdist.macosx-10.12-x86_64/egg/elasticsearch/connection/base.py", line 114, in _raise_error', '    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)', "RequestError: TransportError(400, u'parsing_exception', u'no [query] registered for [not]')"], 'data': {'rule_name': 'High latency routes'}}

elastalert - {'alert_info': {'slack_username_override': 'elastalert', 'type': 'slack', 'slack_webhook_url': ['<url>']}, 'alert_sent': False, 'match_body': {'_type': u'logs', '_index': u'logstash-2017.02.02', u'@timestamp': '2017-02-02T23:31:22.246Z', u'hostname': u'ip-10-0-5-123', '_id': u'AVoBKwyDyTq-epvPpkQa', u'metric': {u'url': u'<sample entry>', u'requestTime': 7285.452803, u'method': u'POST', u'statusCode': 200}}, 'rule_name': 'High latency routes', 'alert_time': datetime.datetime(2017, 2, 3, 9, 31, 22, 246000, tzinfo=tzutc()), 'alert_exception': None}

elastalert_status - {'hits': 9, 'matches': 9, '@timestamp': datetime.datetime(2017, 2, 3, 23, 14, 24, 107566, tzinfo=tzutc()), 'rule_name': 'High latency routes', 'starttime': datetime.datetime(2017, 2, 2, 23, 14, 14, 637396, tzinfo=tzutc()), 'endtime': datetime.datetime(2017, 2, 3, 23, 14, 14, 637396, tzinfo=tzutc()), 'time_taken': 9.288265943527222}
```

**Comment by Qmando** [comment] 2017-02-03 23:23
I don't think you're on the latest version. I removed ``not`` completely from find_pending_aggregate_alert.

You can run ``python -c "import elastalert.elastalert;print elastalert.elastalert.__file__"`` to see while file is actually being used.

**Comment by cwhenderson20** [comment] 2017-02-03 23:38
I had pulled down changes but not re-run the setup scripts. Could that have caused it? I believe it's working now. Is this change also on the support_es5 branch, or just master?

**Comment by cwhenderson20** [comment] 2017-02-03 23:40
Forgot to mention it explicitly: I was testing via `elastalert-test-rule`. I hadn't tried to run elastalert directly.

**Comment by Qmando** [comment] 2017-02-03 23:42
If you installed with ``python setup.py install``, then yes, it's actually copying the source files into your python library folder, so you need to re-install after updating via git.

I merged the support_es5 branch into master. Can't remember if that fix was applied before or after the merge. But that's irrelevant at this point, just use master.

**Comment by cwhenderson20** [comment] 2017-02-03 23:43
Great, thank you! Sorry for the misunderstanding
