### ISSUE TITLE
Circuit Break Exception 

### ISSUE THREAD

**Issue by aniketpant1** [Yelp/elastalert#3070] opened 2020-12-17 16:01 UTC
This issue occurs when window sigma rule run to elastalert
```
file "/usr/local/lib/python3.6/site-packages/elasticsearch-7.0.0-py3.6.egg/elasticsearch/connection/base.py", line 131, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [indices:data/write/bulk[s]] would be [8346603430/7.7gb], which is larger than the limit of [8160437862/7.5gb], real usage: [8346602512/7.7gb], new bytes reserved: [918/918b], usages [request=0/0b, fielddata=3934183583/3.6gb, in_flight_requests=33286/32.5kb, model_inference=0/0b, accounting=158915020/151.5mb]')```

**Comment by nsano-rururu** [comment] 2020-12-17 16:04
https://github.com/Yelp/elastalert/issues/2485

**Comment by aniketpant1** [comment] 2020-12-17 16:29
do i need to install java because i am using java which is already in the elasticsearch

**Comment by nsano-rururu** [comment] 2020-12-17 17:11
https://qiita.com/utti0307/items/a0b89090049dc9c4d47e

**Comment by nsano-rururu** [comment] 2020-12-17 17:12
https://www.elastic.co/guide/en/elasticsearch/reference/7.10/setup.html

**Comment by aniketpant1** [comment] 2020-12-17 17:17
I'd setup this cluster it was working fine but after setting up elastalert i am seeing this i don't where i have to configure either in elasticsearch or in elastalert

**Comment by nsano-rururu** [comment] 2020-12-17 17:26
https://github.com/Yelp/elastalert/issues/2526

**Comment by nsano-rururu** [comment] 2020-12-17 17:27
https://github.com/Yelp/elastalert/issues/1812

**Comment by nsano-rururu** [comment] 2020-12-17 17:28
https://github.com/Yelp/elastalert/issues/1402

**Comment by nsano-rururu** [comment] 2021-04-25 17:44
Yelp/elastalert is no longer maintained. Please use jertel/elastalert2.
https://github.com/jertel/elastalert2

**Comment by balusarakesh** [comment] 2022-03-30 21:21
is there a fix for this?

**Comment by nsano-rururu** [comment] 2022-03-30 23:19
@balusarakesh 
>is there a fix for this?

Not a bug in elastalert.
First, search for "Circuit Break Exception" on google.

**Closed** 2024-06-25 12:52 UTC
