### ISSUE TITLE
Please enable elastalert for elasticsearch 5.0

### ISSUE THREAD

**Issue by amirkool** [Yelp/elastalert#808] opened 2016-11-16 14:41 UTC
I have setup Latest ELK stack with elasticsearch-5.0.0-1.noarch package.
I was trying to setup a blacklist rule.
As expectedd (per current README elastalert lacks support for version 5), It did not worked with my elasticserach stack.
However the same query using curl returned success.

Requesting the development team to add support for version 5(latest) of elasticsearch stack.
Thank you!

**Comment by timwsuqld** [comment] 2016-11-16 21:56
Duplicate of #790

**Closed** 2016-11-17 01:16 UTC
